webhooks:
  - name: Render Deploy
    type: PULL_REQUEST
    command: 
      - "bash"
      - "-c"
      - "npm install && npm start"

builds:
  - name: md-preview-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
